import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-DEFER9ZCKT"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-DEFER9ZCKT');
      </script>
        <title>Air Details | Harvard Business Review</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.instagram.com/miguelgargallo.es/">Air Details</a>
        </h1>

        <p className={styles.description}>
          Colaborando con HBR, Estudiante de Harvard{' '}
          <code className={styles.code}>🎉 Over 250K Viewers and 22K Followers</code>
        </p>

        <div className={styles.grid}>
          <a 
          href="https://express.adobe.com/page/sTLdQH7sQVsgb/index.html" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>PREMIOS ESLAND &rarr;</h2>
            <p>IBAI, El Xokas, IlloJuan, Jordi Wild, Jagger ...  The Grefg!.</p>
          </a>

          <a href="https://express.adobe.com/page/OopViOPVJhVgV/index.html" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>FCB &rarr;</h2>
            <p>Barça, Barça B, Femení, Bàsquet, Events Burocràtics i Hockey.</p>
          </a>

          <a href="https://express.adobe.com/page/podDpYbThdPUR/index.html" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>TESLA MOTORS &rarr;</h2>
            <p>Model X, Barcelona EXPO.</p>
          </a>

          <a href="https://express.adobe.com/page/t6UQMW9VDePJP/index.html" target="_blank" rel="noopener noreferrer" className={styles.card}>
            <h2>Turisme Catalunya &rarr;</h2>
            <p>Professional Drone Pilot, Mavic 3 Pro.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://itamaesan.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed by{' '}
          <span className={styles.logo}>
            <a>ITAMAESAN ORG</a>
          </span>
        </a>
      </footer>
    </div>
  )
}
